version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: estudo
    volumes:
      - ./data/pgdata/:/var/lib/postgresql/data/
    networks:
      - apidb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: andersonhsantanappa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 5050:80
    depends_on:
      - db
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/
    networks:
      - apidb

networks:
  apidb:

volumes:
  postgres:
  pgadmin:
